### ISSUE TITLE
missing from tree when used in addon

### ISSUE THREAD

**Issue by kellyselden** [dfreeman/ember-css-modules-sass#1]
Follwing https://github.com/salsify/ember-css-modules#usage-in-addons, it appears when using sass, the file doesn't exist to import:

```
Error: Could not find module `checkout/styles/components/flow/account-info` imported from `checkout/components/flow/account-info`
    at missingModule (loader.js:244)
    at findModule (loader.js:255)
    at Module.findDeps (loader.js:165)
    at findModule (loader.js:259)
    at Module.findDeps (loader.js:165)
    at findModule (loader.js:259)
    at requireModule (loader.js:26)
    at Class._extractDefaultExport (index.js:387)
    at Class.resolveOther (index.js:108)
    at Class.superWrapper [as resolveOther] (ember.debug.js:45374)
```

**Comment by dfreeman** [comment]
@kellyselden definitely seems like a bug. Any chance this is in a public repo? Otherwise I'll see if I can reproduce myself later tonight.

**Comment by kellyselden** [comment]
It's not, but I'm running a very basic in-repo-addon where I need to bundle the layout and styles. It works with css modules, but then adding the sass deps and renaming files to scss triggered the bug.

**Comment by dfreeman** [comment]
Seems to be working [here](https://github.com/dfreeman/in-repo-sass/commit/e36b76b2490b968ebc75d51465a40de1969bebf0) — can you spot anything there that's different from your setup?

**Comment by kellyselden** [comment]
Appologies for wasting your time :(
I forgot to add the new addons to the in-repo-addon's dependencies...

**Comment by dfreeman** [comment]
No worries! Glad it wound up being something easy to fix :)
